In [ ]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

In [ ]:
data = load_breast_cancer()

In [ ]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
feature = data['data']
labels  = data['target']

scaling  = StandardScaler()
features = scaling.fit_transform(feature)

In [ ]:
print(features.shape)
print(labels.shape)

(569, 30)
(569,)


In [ ]:
model = Sequential()

model.add(Dense(15, activation = 'relu', input_dim = 30))
# model.add(Dropout(0.2))

model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
h = model.fit(features,labels, epochs = 50, validation_split = 0.2, batch_size = 1)

Epoch 1/50
455/455 [==============================] - 1s 1ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 0.1933 - val_accuracy: 0.9211
Epoch 2/50
455/455 [==============================] - 1s 1ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 0.1110 - val_accuracy: 0.9649
Epoch 3/50
455/455 [==============================] - 1s 1ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 0.1325 - val_accuracy: 0.9561
Epoch 4/50
455/455 [==============================] - 1s 1ms/step - loss: 9.6730e-04 - accuracy: 1.0000 - val_loss: 0.1171 - val_accuracy: 0.9649
Epoch 5/50
455/455 [==============================] - 1s 1ms/step - loss: 7.9662e-04 - accuracy: 1.0000 - val_loss: 0.1199 - val_accuracy: 0.9649
Epoch 6/50
455/455 [==============================] - 1s 1ms/step - loss: 7.8550e-04 - accuracy: 1.0000 - val_loss: 0.1168 - val_accuracy: 0.9649
Epoch 7/50
455/455 [==============================] - 1s 1ms/step - loss: 6.2429e-04 - accuracy: 1.0000 - val_loss: 0.1617 - val_accurac

In [ ]:
features[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [ ]:
labels[20]

1

In [ ]:
d = np.reshape(features[20], (1,30))

In [ ]:
d

array([[-0.29744572, -0.83300824, -0.26110605, -0.38363845,  0.79276301,
         0.42942187, -0.54136176, -0.45962673,  0.56728859,  0.75308658,
        -0.79392535, -0.85120566, -0.73415971, -0.56471962, -0.98136609,
        -0.36317799, -0.49449443, -0.86070672, -0.4555335 , -0.51816798,
        -0.3663683 , -0.84470709, -0.33274394, -0.43962431, -0.05122636,
         0.14844292, -0.39909871, -0.63610973,  0.45822712, -0.11724974]])

In [ ]:
if (model.predict(d)[0][0] < 0.5):
  print("Congo")
else:
  print("XYZ")

XYZ


In [ ]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,